theme: jekyll-theme-minimal
title: 虚拟的世界
logo: https://avatars3.githubusercontent.com/u/23043352?s=460&v=4
author: joleensteve
excerpt_separator: <!--more-->
paginate: 5
leancloud:
  enable: true
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
